config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: "users/registrations",
                                      sessions: "users/sessions" }

 

  resources :profiles do 
       resources :posts

   end
   root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/post.rb
class Post < ApplicationRecord
  include ImageUploader::Attachment.new(:image)
  
  belongs_to :profile

end

app/models/profile.rb
class Profile < ApplicationRecord

    belongs_to :user
    has_many :posts
    
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable

    has_many :posts

    has_one :profile, dependent: :destroy
    after_create :init_profile
  
    def init_profile
      self.create_profile!
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!

  protect_from_forgery with: :null_session

    private
  
      def after_sign_in_path_for(resource)
        profile_posts_path [:profile_id]
        end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @current_user_profile = current_user.profile # Profile.where(user_id: current_user.id)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
    @current_user_profile = current_user.profile
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:posts).permit(:picture, :price, :description)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:username, :picture, :bio)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]
  
   # GET /resource/sign_up
     def new
       super
     end
  
   # POST /resource
     def create
       super
     end
  
   # GET /resource/edit
     def edit
       super
     end
  
   # PUT /resource
     def update
       super
     end
  
   # DELETE /resource
     def destroy
       super
     end
  
   # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end
  
   # protected
  
   # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end
  
   # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end
  
   # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end
  
   # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  
  
  
  
   private
  
     # Modified Devise params for user login
      def sign_up_params
        params.require(:user).permit(:email, :password, :password_confirmation)
      end
  
     def after_sign_up_path_for(resource)
      profile_posts_path [:profile_id]
  
     end
  
     def after_inactive_sign_up_path_for(resource)
        “/newuser”
      end
  
  
  end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]
  
    # GET /resource/sign_in
    # def new
    #   super
    # end
  
    # POST /resource/sign_in
    def create
       super
    end
  
    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end
  
    # protected
  
    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hypevintage</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
    integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
    crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  <%= render 'partials/index' %>
    <%= render 'partials/navbar' %>

    <%= yield %>

  </body>

</html>

app/views/partials/_index.html.erb
<div class="container-logo">
  <div class="col-12 col-sm-8 col-md-8 col-lg-12 text-center">
<!-- Best Img TAG -->
<%= image_tag("Hype Vintage.png", class: "logo") %>

</div>
</div>

# <!-- <div class="card" style="width: 20rem;">
#  <%= image_tag("Hype Vintage.png") %>
#   <div class="card-block">
#     <h4 class="card-title">Card title</h4>
#     <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
#     <a href="#" class="btn btn-primary">Go somewhere</a>
#   </div>
# </div> -->

app/views/partials/_navbar.html.erb
<div class="container-fluid">
<nav class="nav">

  <% if user_signed_in? %>

    <a class="btn" href="#" role="button"> New Products </a>
    <a class="btn" href="#" role="button"> Brands </a>
    <a class="btn" href="#" role="button"> Contact </a>

    <li>
      <%= link_to('Logout', destroy_user_session_path, method: :get) %>
        </li>

    <li>
      <%= link_to('Edit registration', edit_user_registration_path) %>
        </li>

  <% end %>

  <% if !user_signed_in? && request.path != "/users/sign_in" %>
    <li>
      <%= link_to('Login', new_user_session_path)  %>
        </li>
  <% end %>

  <% if !user_signed_in? && request.path != "/users/sign_up" %>
    <li>
      <div class="btn">
      <%= link_to('Register', new_user_registration_path)  %>
      </div>
      </li>
  <% end %>

</nav>
</div>

app/views/posts/_form.html.erb
<div class="container-fluid">
 <%= form_with url: profile_posts_path(@current_user_profile), local: true do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if post.picture.present? %>
      <%= image_tag post.image_url %>
    <% end %>

    <%= form.label :image %>

    <%= form.file_field :image %>

  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

</div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container-fluid">
  <h1>Posts</h1>
    <div class="btn">
    <%= link_to 'New Post', new_profile_post_path(@current_user_profile.id) %>
    </div>

  <div class="row">
    <div class="container-1 col-sm-12">
      <% @posts.reverse_each do |post, index| %>
      <div class="card">
        <div class="card-block">
        <div class="box-<%= index %>">
          <img src="<%= post.image_url %>" class="posts-images">
          <h4 class="card-title"><p><%= post.description %></p></h4>
          <p>
            <%= link_to 'Show', post %> |
            <%= link_to 'Edit', edit_post_path(post) %> |
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          </p>
        </div>
        </div>
      </div>

      <% end %>
    </div>
  </div>

</div>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', root_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">

<p>
  <% if @post.image.present? %>
    <%= image_tag @post.image_url %>
    <%= @post.description %>
    <strong><%= current_user.email %></strong>
  <% end %>
</p>
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_area :username, id: :profile_username %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_area :picture, id: :profile_picture %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_field :bio, id: :profile_bio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Picture</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.username %></td>
        <td><%= profile.picture %></td>
        <td><%= profile.bio %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @profile.username %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @profile.picture %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @profile.bio %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>